### ISSUE TITLE
Add methos to send custom json to the cat via WS

### ISSUE THREAD

**Issue by cristianorevil** [cheshire-cat-ai/api-client-py#11]
### 🚀 The feature, motivation and pitch

The actually send method (cat_client.py line 120) send a ws message with only "text" parameter. To permit a better integrations with 3rd party tools can be useful to have a second method (eg send_with_params) that permit to send a custom json in additional to text, eg:

"text": message,
"custom_settings": json_string

Obviously this additional setting need to be managed by a plugin on cat server side.

**Comment by nicola-corbellini** [comment]
Hello! This is already possible using `kwargs` in the `send` method

**Comment by cristianorevil** [comment]
Oh sorry, there is some examples?

**Comment by nicola-corbellini** [comment]
actually not, the documentation should be improved.
Here is an example
```python
# assuming you have instantiated the client
cat_client.send(text="your text", custom_key=42, custom_key2="another string")
```
the JSON to be sent will be
```json
{
   "text": "your text",
   "custom_key": 42,
   "custom_key2": "another string"
}
```
