### ISSUE TITLE
Configuration for the rabbit hole api doesn't work without specifying host even though docs says it is optional

### ISSUE THREAD

**Issue by DavideRichini** [cheshire-cat-ai/api-client-py#12]
### 🐛 Describe the bug

`from cheshire_cat_api.api.rabbit_hole_api import RabbitHoleApi
from cheshire_cat_api.api_client import ApiClient
from cheshire_cat_api.configuration import Configuration

file=open("example.txt","w")

conf = Configuration()
api_client=ApiClient(conf)
api_instance = RabbitHoleApi(api_client)
api_response = api_instance.upload_file("example.txt")`

this snippet creates an empty txt file and tries to upload it through the rabbit hole api and fails because the host isn't specified

I believe this is a bug because the [rabbit hole api docs](https://github.com/cheshire-cat-ai/api-client-py/blob/main/docs/RabbitHoleApi.md) say  `# Defining the host is optional and defaults to http://localhost`

### Versions

Python 3.10.11
annotated-types==0.6.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
cheshire_cat_api==1.4.1
cryptography==42.0.5
idna==3.6
pdfminer.six==20221105
pdfplumber==0.10.4
Pillow==9.5.0
pycparser==2.21
pycryptodome==3.16.0
pydantic==2.6.2
pydantic_core==2.16.3
PyPDF2==3.0.1
pypdfium2==4.27.0
python-dateutil==2.8.2
requests==2.31.0
six==1.16.0
soupsieve==2.5
typing_extensions==4.9.0
urllib3==2.0.7
websocket-client==1.7.0

**Comment by nicola-corbellini** [comment]
Hi! This is not the intended way to use the client. Sorry, I should remove that documentation.
Take a look [here](https://github.com/cheshire-cat-ai/api-client-py?tab=readme-ov-file#rabbithole-api---upload-a-url), there is an example snippet to upload a file. Namely:
```python
import cheshire_cat_api as ccat
from cheshire_cat_api.models.body_upload_url import BodyUploadUrl

# A config is necessary to set up base parameters like
# URL, port, user_id, etc.
config = ccat.Config(user_id="my_user_42")

# Connect to the API
cat_client = ccat.CatClient(
    config=config
)

# Please note that interacting with the RabbitHole to upload
# a URL requires structuring the body like this

body_upload_url = BodyUploadUrl(
    url="https://cheshire-cat-ai.github.io/docs/conceptual/cheshire_cat/rabbit_hole/"
)

# then you can make the request as follows
response = cat_client.rabbit_hole.upload_url(body_upload_url)
```

**Comment by nicola-corbellini** [comment]
I realized I pasted the example to upload a url, the code for a file is
```python
response = cat_client.rabbit_hole.upload_file(file_path)
```

**Comment by DavideRichini** [comment]
Thank you for the response. It makes sense that it is not the intended behaviour but I was confused by the documentation.
Would it be ok for me to send a pr with fixes to the documentation of the rabbir hole api? Because the current example for the upload_file method deosn't even run.

**Comment by nicola-corbellini** [comment]
Which error do you get? 
If you want to make a pr to fix the documentation you linked, that should be removed completely since it is autogenerated.
It would be nice, but demanding to have a nice docs like the one of the cat with mkdocs and hosted on github pages.
If you feel like setting this up would be a huge contribution

**Comment by DavideRichini** [comment]
I get this error
`Traceback (most recent call last):
  File "D:\stregatto\a.txt", line 9, in <module>
    configuration = cheshire_cat_api.Configuration(
AttributeError: module 'cheshire_cat_api' has no attribute 'Configuration'. Did you mean: 'configuration'?`

It is caused because the class is Configuration while the file is all lowercase so you need to import it with 
`from cheshire_cat_api.configuration import Configuration`

If I want to contribute to the docs the correct way should be by contributing to [this repo](https://github.com/cheshire-cat-ai/docs), right?

**Comment by nicola-corbellini** [comment]
Please, take a look at the whole code in the snippet I shared before. This is how you import the config
```python
import cheshire_cat_api as ccat
from cheshire_cat_api.models.body_upload_url import BodyUploadUrl

# A config is necessary to set up base parameters like
# URL, port, user_id, etc.
config = ccat.Config(user_id="my_user_42")
```

**Comment by DavideRichini** [comment]
Your code snipped does work. What I was saying is that the example code for the upload_file method in the documentation does not work because of a wrong import.

**Comment by nicola-corbellini** [comment]
Yes, that documentation is autogenerated and should be removed

**Comment by nicola-corbellini** [comment]
If the bug is solved I'm closing the issue, feel free to open it again if you have any other trouble
